name: penguin-noses
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: r-lib/actions/setup-r@master
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          apt-get update -y 
          apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev
          
          Rscript penguin_analysis.R
          
          cml-publish my_penguing_plot.png --md > report.md
          cat model.html >> report.md 
          cml-send-comment report.md
